# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shorty}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Coomans"]
  s.date = %q{2009-11-23}
  s.description = %q{Makes it easy to shorten URLs}
  s.email = %q{alex@alexcoomans.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/bitly.feature",
     "features/step_definitions/api.rb",
     "features/step_definitions/common_steps.rb",
     "features/support/common.rb",
     "features/support/env.rb",
     "features/support/matchers.rb",
     "features/trim.feature",
     "lib/shorty.rb",
     "lib/shorty/bitly.rb",
     "lib/shorty/cligs.rb",
     "lib/shorty/isgd.rb",
     "lib/shorty/supr.rb",
     "lib/shorty/tinyurl.rb",
     "lib/shorty/to_openstruct.rb",
     "lib/shorty/trim.rb",
     "lib/shorty/twurl.rb",
     "shorty.gemspec",
     "test/bitly_test.rb",
     "test/cligs_test.rb",
     "test/fixtures/bitly-expand-cnn.json",
     "test/fixtures/bitly-shorten-cnn.json",
     "test/fixtures/bitly-stats-cnn.json",
     "test/fixtures/cligs-shorten-google.txt",
     "test/fixtures/isgd-shorten-google.txt",
     "test/fixtures/supr-expand-cnn-error.json",
     "test/fixtures/supr-expand-cnn.json",
     "test/fixtures/supr-shorten-cnn.json",
     "test/fixtures/tinyurl-shorten-google.txt",
     "test/fixtures/trim-trim-simple.txt",
     "test/fixtures/trim-trim-url.xml",
     "test/fixtures/twurl-shorten-google.txt",
     "test/isgd_test.rb",
     "test/shory_test.rb",
     "test/supr_test.rb",
     "test/test_helper.rb",
     "test/tinyurl_test.rb",
     "test/trim_test.rb",
     "test/twurl_test.rb"
  ]
  s.homepage = %q{http://github.com/drcapulet/shorty}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem that talks to APIs for shortening urls}
  s.test_files = [
    "test/bitly_test.rb",
     "test/cligs_test.rb",
     "test/isgd_test.rb",
     "test/shory_test.rb",
     "test/supr_test.rb",
     "test/test_helper.rb",
     "test/tinyurl_test.rb",
     "test/trim_test.rb",
     "test/twurl_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.4"])
      s.add_runtime_dependency(%q<crack>, [">= 0.1.4"])
    else
      s.add_dependency(%q<httparty>, [">= 0.4.4"])
      s.add_dependency(%q<crack>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.4.4"])
    s.add_dependency(%q<crack>, [">= 0.1.4"])
  end
end

